INSERT INTO car (car_picture, car_full_name, car_Serialnr, car_number, car_model, car_name, car_year, monthly_price, is_leased, car_description) VALUES ('Peugeot_E-3008_GT_0MM00NDP.png','Peugeot E-3008 GT 210 HK','LS123456','VR12316','E-3008 GT','Peugeot',2000,5000,1,'Dette er en beskrivelse af bilen');
INSERT INTO car (car_picture, car_full_name, car_Serialnr, car_number, car_model, car_name, car_year, monthly_price, is_leased, car_description) VALUES ('Fiat_500e_Icon_601.png','Fiat 500e Icon 118 HK','LS123126','SB12332','500e Icon','Fiat',2009,5500,1,'Dette er en beskrivelse af bilen');
INSERT INTO car (car_picture, car_full_name, car_Serialnr, car_number, car_model, car_name, car_year, monthly_price, is_leased, car_description) VALUES ('Volkswagen_Caravelle_Comfortline_GRAA.png','VW Caravelle Comfortline 150 HK','LS123123','ED12332','Comfortline','VW Caravelle',2012,4500,0,'Dette er en beskrivelse af bilen');
INSERT INTO car (car_picture, car_full_name, car_Serialnr, car_number, car_model, car_name, car_year, monthly_price, is_leased, car_description) VALUES ('Citroen_newc3_VTRSport_0MM00NVL.png','Citroën C3 VTR Sport 83 HK','LS951359','MP12312','C3 VTR Sport','Citroën',1997,4600,0,'Dette er en beskrivelse af bilen');
INSERT INTO car (car_picture, car_full_name, car_Serialnr, car_number, car_model, car_name, car_year, monthly_price, is_leased, car_description) VALUES ('Varebiler_Lille-el_Lille-el_0MM60NN9_dimension-Dimensioner.png','Lille Elektrisk Varebil','LS426319','VB12312','Test Model','Test Mærke',2024,3000,1,'Dette er en beskrivelse af elbilen');

INSERT INTO damagereport (report_name, report_description, report_employee_name, report_Damage_Date, car_id) VALUES ('Skaderapport for Kunde #55', 'Dette er en beskrivelse af rapporten', 'Henrik Testperson', '2024-05-01', 1);
INSERT INTO damagereport (report_name, report_description, report_employee_name, report_Damage_Date, car_id) VALUES ('Skaderapport for Kunde #57', 'Dette er en beskrivelse af rapporten', 'Flemming Testperson', '2024-04-21', 2);
INSERT INTO damagereport (report_name, report_description, report_employee_name, report_Damage_Date, car_id) VALUES ('Skaderapport for Kunde #58', 'Dette er en beskrivelse af rapporten', 'Bo Testperson', '2024-03-15', 3);
INSERT INTO damagereport (report_name, report_description, report_employee_name, report_Damage_Date, car_id) VALUES ('Skaderapport for Kunde #59', 'Dette er en beskrivelse af rapporten', 'Niels Testperson', '2024-02-09', 4);
INSERT INTO damagereport (report_name, report_description, report_employee_name, report_Damage_Date, car_id) VALUES ('Skaderapport for Kunde #60', 'Dette er en beskrivelse af rapporten', 'Charlie Testperson', '2023-12-24', 5);

INSERT INTO leasingcontract (employee_name,monthly_price,customer_name,start_leasing,end_leasing,is_unlimited,is_limited,car_id) VALUES ('Henrik Testperson',5500,'Benny Kunde','2024-01-20','2024-03-15',0,1,1);
INSERT INTO leasingcontract (employee_name,monthly_price,customer_name,start_leasing,end_leasing,is_unlimited,is_limited,car_id) VALUES ('Flemming Testperson',5000,'Nancy Kunde','2024-01-23','2024-03-23',0,1,2);
INSERT INTO leasingcontract (employee_name,monthly_price,customer_name,start_leasing,end_leasing,is_unlimited,is_limited,car_id) VALUES ('Charlie Testperson',5000,'John Kunde','2024-01-25','2024-06-10',1,0,5);

INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('punkteret dæk',250,'begge dæk på venstre side er punkteret', 1);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('smadret bilrude',1650,'bilens bagrude er smadret', 1);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Buler i karrosseriet',2500,'Små buler på karrosseriet, ofte forårsaget af parkeringsskader eller mindre kollisioner.', 2);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Ridser i lakken',1200,'Overfladeridser på bilens lak, som kan opstå ved kontakt med grene, nøgler eller andre skarpe genstande.', 2);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Knust forlygte',3000,'Forlygten er knust eller beskadiget, ofte som resultat af et frontalt sammenstød eller stenkast.', 3);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Sprunget forrude',5500,'Forruden er revnet eller sprunget, hvilket kan ske ved stenkast eller pludselige temperaturændringer.', 3);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Ødelagt kofanger',4000,'Kofangeren er revnet eller skæv, typisk som følge af en kollision ved lav hastighed.', 4);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Knækket sidespejl',2200,'Sidespejlet er knækket eller beskadiget, ofte som resultat af at bilen bliver ramt af en forbipasserende bil eller cyklist.', 4);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Skade på undervognen',6500,'Skader på bilens undervogn, som kan opstå ved at køre over store forhindringer eller hul i vejen.', 5);
INSERT INTO damages (damage_name,damage_price,damage_description,damagereport_id) VALUES ('Beskadiget udstødningssystem',4500,'Skader på udstødningsrøret eller lydpotten, som kan opstå ved kollisioner eller rust.', 5);
